project:
  type: website
  output-dir: docs

website:
  title: "GEOS 270 Final Exam"
  navbar:
    left:
      - href: index.qmd
        text: " "

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



